### ISSUE TITLE
Support rendering diagrams from text format

### ISSUE THREAD

**Issue by gberche-orange** [pivotal-cf/bookbinder#105]
It is sometimes hard for cf community to contribute fix to existing diagrams in docs-* repos as often the source files used to produce them is missing, or requires specific OS/License to modify it and generate a new image (PNG, JPG). See related [service broker thread](http://cf-dev.70369.x6.nabble.com/cf-dev-Announcing-Experimental-support-for-Asynchronous-Service-Operations-tp287p1432.html) as an example.

It would be great if bookbinder would support rendering diagrams from a text format such as the opensource [plantuml](http://plantuml.com/sequence.html) format, and generate static PNG from the plant uml source, or alternatively rely on [plantuml public service](http://plantuml.com/plantuml/) for such rendering.

**Comment by animatedmax** [comment]
Thank you for this suggestion, gberche-orange -- I think this is a great idea, and I've added an exploratory charter to the Pub Tools tracker to see what it will take to add this feature.

**Comment by gberche-orange** [comment]
Thanks @animatedmax ! 

BTW, it seems the "Pub tools" pivotal tracker project you mention is not yet public (I'm getting "You are not allowed to view the requested page."). Any chance to open it up as to allow the community to follow discussions/progress on this ?

**Comment by animatedmax** [comment]
Hi @gberche-orange 

Unfortunately, we can't make the Pub Tools tracker public. The team works on Bookbinder, which is open source, but also works on projects that have to remain private. Nevertheless, we'll work to keep the community updated on this and other Bookbinder features. 

Thank you!

**Comment by animatedmax** [comment]
Hi @gberche-orange

Bookbinder 7.1.0 now supports rendering diagrams from text format.

Bookbinder's `mermaid_diagram` helper accepts a block that includes text formatted to generate   [Mermaid](https://github.com/knsv/mermaid) diagrams. In order to use this helper, you must include the [Mermaid package](http://knsv.github.io/mermaid/usage.html#installation) in your book.

Example usage:

<% mermaid_diagram do%>
 graph TB
         subgraph one
         a1-->a2
         end
         subgraph two
         b1-->b2
         end
         subgraph three
         c1-->c2
         end
         c1-->a2
<% end %>

**Comment by gberche-orange** [comment]
Great, thanks @animatedmax. I'll be trying this next and providing feedback, including flexibility in the mermaid syntax. I'll be trying the [live editor](http://knsv.github.io/mermaid/live_editor/) as a 1st step to avoid setting up a full local nodejs for diagram previews.

BTW, do you know if bosh.io uses bookbinder and thus if https://github.com/cloudfoundry/docs-bosh would accept PR including mermaid diagrams ?

**Comment by animatedmax** [comment]
I'm not sure if bosh.io uses bookbinder or not. Sorry!

**Comment by kimahoff** [comment]
bosh.io does not use bookbinder.
