### ISSUE TITLE
elastic_search undocumented

### ISSUE THREAD

**Issue by mastertinner** [pivotal-cf/bookbinder#109]
Can anybody tell me how the elastic_search flag works? If I enable it, where can I give the app the respective credentials and URL to my elastic search instance? Are there any alternatives (e.g. the Google Custom Search Engine which was offered a couple of versions ago and which was used by Pivotal)?

**Comment by animatedmax** [comment]
Hi @mastertinner 
Answering your questions in reverse:

If you do not enable ElasticSearch, you should be able to use the Google Custom Search Engine as you did before, with no changes.

If you enable ElasticSearch in your book, the only way we currently have of implementing it is to run your book's app on PWS, then add ElasticSearch as a Service and bind it to the book app.

Hope that helps!

**Comment by mastertinner** [comment]
Thanks, @animatedmax!
