### ISSUE TITLE
In-page anchors break h3 headings without h2

### ISSUE THREAD

**Issue by fifthposition** [pivotal-cf/bookbinder#110]
If I have page that starts with a level-3 heading:

```
### Introduction
```

and then add an `<a>` for an in-page link:

```
## <a id="introduction"></a>Introduction
```

I get an error:

> The header "<a id="introduction"></a>Introduction", which is at level 3, has no higher-level headers occurring before it.

The page builds fine _without_ the anchor tag. When I add that, I get the error. So I can’t have a page that has an in-page TOC and starts with an h3. (Level-2 headings don’t seem to have this problem.)

Is this intended behavior? I could see headings being _out_ of order as a problem, but in the case I am on, it’d be nice to go on using h3 headings for the sections, and the page title will already be an h1, so it’d be nice to be able to start a page with any level heading so long as the heading levels were in the correct order.

**Comment by animatedmax** [comment]
Hi Ben,

Yes, it is intended that Bookbinder throws an error when you have an in-page TOC (or "quick links") and start with a level 3 header. We made this choice to ensure the formatting of the in-page TOC was consistent, and as part of our effort to help enforce accessibility compliance. (Properly nested heading elements as described here: https://www.w3.org/TR/2012/NOTE-WCAG20-TECHS-20120103/G141).

All that being said, I've changed the issue to a feature request and moved it to the Pub Tools backlog. https://www.pivotaltracker.com/story/show/126826443

In the meantime, have you considered using an h2 as the first element, but adding HTML styles directly to it to make it look like an h3? I'm not sure how well it would work, or if it would give you the look you're looking for, but I can have someone from the CF Docs team reach out to you to assist if you think it might be helpful.

Thanks!
